#!/usr/bin/env python3
"""Emit a C++ header holding a complex-script layout font for built-in fonts.

usage: gen_builtin_shaping_layout.py FONT SYMBOL [--scripts devanagari] > SYMBOL.h

The array is what BuiltinShapingFace::layout points at (see BuiltinShaping.h):
the same layout font a .cpfont shaping section carries, read in place from
flash. fontconvert.py --shaping-layout-symbol SYMBOL references it.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import shaping_blob  # noqa: E402

parser = argparse.ArgumentParser()
parser.add_argument("font")
parser.add_argument("symbol")
parser.add_argument("--scripts", default="devanagari")
args = parser.parse_args()

scripts = [name.strip() for name in args.scripts.split(",") if name.strip()]
_, layout, glyph_count = shaping_blob.build(args.font, scripts)
print(f"""/**
 * generated by gen_builtin_shaping_layout.py
 * font: {os.path.basename(args.font)}
 * scripts: {', '.join(scripts)}
 * {len(layout)} bytes, {glyph_count} glyphs, FNV-1a 0x{shaping_blob.fnv1a32(layout) | 1:08X}
 */
#pragma once
#include <cstdint>

// clang-format off
alignas(4) inline constexpr uint8_t {args.symbol}[{len(layout)}] = {{""")
for i in range(0, len(layout), 16):
    print("    " + ", ".join(f"0x{b:02X}" for b in layout[i:i + 16]) + ",")
print("};")
print("// clang-format on")
