#!/usr/bin/env python3
"""Expected HarfBuzz glyph ids for every built-in Indic font, for the C3 test.

    gen_all_scripts.py <texts-dir> > include/AllScriptsExpected.h

<texts-dir> holds <script>-story.txt for each script (test/indic/texts). From
each story it takes the WORDS longest distinct words of that script, shapes
them with HarfBuzz (uharfbuzz) in the same subset of Noto Sans Regular the
firmware embeds (shaping_blob.build, so glyph ids match its tokens), and
writes their glyph ids. It also keeps the story's opening as the
paragraph whose bitmaps the test loads.
"""
import os
import re
import sys

import uharfbuzz as hb

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../lib/EpdFont/scripts"))
import shaping_blob  # noqa: E402

SCRIPTS = [  # name, font dir, first codepoint of the block, story file[, block size]
    ("devanagari", "NotoSansDevanagari", 0x0900, "hindi"),
    ("bengali", "NotoSansBengali", 0x0980, "bengali"),
    ("gurmukhi", "NotoSansGurmukhi", 0x0A00, "punjabi"),
    ("gujarati", "NotoSansGujarati", 0x0A80, "gujarati"),
    ("oriya", "NotoSansOriya", 0x0B00, "odia"),
    ("tamil", "NotoSansTamil", 0x0B80, "tamil"),
    ("telugu", "NotoSansTelugu", 0x0C00, "telugu"),
    ("kannada", "NotoSansKannada", 0x0C80, "kannada"),
    ("malayalam", "NotoSansMalayalam", 0x0D00, "malayalam"),
    ("sinhala", "NotoSansSinhala", 0x0D80, "sinhala"),
    ("myanmar", "NotoSansMyanmar", 0x1000, "burmese", 0xA0),
]
WORDS = 24
PARAGRAPH_CHARS = 240
FONTS = os.path.join(os.path.dirname(__file__), "../../../lib/EpdFont/builtinFonts/source")


def c_string(text):
    return '"' + "".join(f"\\x{b:02X}" for b in text.encode("utf-8")) + '"'


def script_words(text, first, size=0x80):
    joiners = "‌‍"
    pattern = f"[{chr(first)}-{chr(first + size - 1)}{joiners}]+"
    seen = []
    for word in re.findall(pattern, text):
        word = word.strip(joiners)
        if word and word not in seen:
            seen.append(word)
    # Longest first (most conjuncts and signs), then the joiner-bearing ones
    # the shaper treats specially.
    longest = sorted(seen, key=lambda w: (-len(w), w))[:WORDS]
    with_joiners = [w for w in seen if ("‌" in w or "‍" in w) and w not in longest][:4]
    return longest + with_joiners


def shape(font, word):
    buf = hb.Buffer()
    buf.add_str(word)
    buf.guess_segment_properties()
    hb.shape(font, buf, {})
    return [info.codepoint for info in buf.glyph_infos]


def main():
    texts = sys.argv[1]
    out = ["#pragma once", "// Generated by gen_all_scripts.py from test/indic/texts. Do not edit.", "",
           "#include <cstddef>", "#include <cstdint>", "",
           "struct ScriptWord {", "  const char* utf8;", "  const uint16_t* gids;", "  uint8_t count;", "};", ""]
    table = []
    for name, font_dir, first, story_name, *size in SCRIPTS:
        path = os.path.join(FONTS, font_dir, f"{font_dir}-Regular.ttf")
        render_bytes, _, _ = shaping_blob.build(path, [name])
        font = hb.Font(hb.Face(hb.Blob(render_bytes)))
        story = open(os.path.join(texts, f"{story_name}-story.txt"), encoding="utf-8").read()
        words = script_words(story, first, *size)
        entries = []
        for i, word in enumerate(words):
            gids = shape(font, word)
            out.append(f"constexpr uint16_t k_{name}_{i}[] = {{{', '.join(map(str, gids))}}};")
            entries.append(f"    {{{c_string(word)}, k_{name}_{i}, {len(gids)}}},")
        out.append(f"constexpr ScriptWord k_{name}_words[] = {{")
        out.extend(entries)
        out.append("};")
        body = " ".join(line.strip() for line in story.splitlines()[1:] if line.strip())
        paragraph = body[:PARAGRAPH_CHARS].rsplit(" ", 1)[0]
        out.append(f"constexpr const char* k_{name}_paragraph = {c_string(paragraph)};")
        out.append("")
        table.append(name)
    out.append("#define ALL_SCRIPTS_EXPECTED(X) \\")
    out.append(" \\\n".join(f"  X({name})" for name in table))
    print("\n".join(out))


if __name__ == "__main__":
    main()
